### ISSUE TITLE
Julia 1.4 Compatibility

### ISSUE THREAD

**Issue by Sinansi** [baggepinnen/AdaptiveFilters.jl#2]
Hello,

I am trying to install the AdaptiveFilters.jl package on Julia 1.4 but it gives compilation error.
What is the latest Julia version the package is compatible with?

Thank you!

[ Info: Precompiling AdaptiveFilters [c4f366c8-f60d-49ea-b3e5-386989159d04]
WARNING: could not import LearnBase.fit! into OnlineStats
WARNING: could not import LearnBase.nobs into OnlineStats
WARNING: could not import LearnBase.predict into OnlineStats
ERROR: LoadError: UndefVarError: prox not defined
Stacktrace:
 [1] include(::Module, ::String) at .\Base.jl:377
 [2] top-level scope at none:2
 [3] eval at .\boot.jl:331 [inlined]
 [4] eval(::Expr) at .\client.jl:449
 [5] top-level scope at .\none:3
in expression starting at C:\Users\Sannan\.julia\packages\OnlineStats\iY7aT\src\OnlineStats.jl:17
ERROR: LoadError: Failed to precompile OnlineStats [a15396b6-48d5-5d58-9928-6d29437db91e] to C:\Users\Sannan\.julia\compiled\v1.4\OnlineStats\G3mU6_ocvKB.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] include(::Module, ::String) at .\Base.jl:377
 [7] top-level scope at none:2
 [8] eval at .\boot.jl:331 [inlined]
 [9] eval(::Expr) at .\client.jl:449
 [10] top-level scope at .\none:3
in expression starting at C:\Users\Sannan\.julia\packages\AdaptiveFilters\MvfL3\src\AdaptiveFilters.jl:2

**Comment by baggepinnen** [comment]
Hello!
I'm not seeing any problems on julia v1.4. Have you loaded some other package before you loaded AdaptiveFilters? Which version of AdaptiveFilters do you have installed and what happens if you install and load the package in a fresh environment?

**Comment by Sinansi** [comment]
@baggepinnen I have traced the error again. It is a dependency issue. I have explicitly installed OnlineStats.jl but couldnt load it. I sent a message to its developers and they mentioned that a new faulty LearnBase was released, and they currently fixing the issue.

https://github.com/joshday/OnlineStats.jl/issues/199#issue-607895222

Thank you!

**Comment by baggepinnen** [comment]
Great! :)

**Comment by Sinansi** [comment]
This issue has been solved. The underlying dependencies have been fixed and I was able to install AdaptiveFilters.jl on Julia 1.4.

All good! Thank you!
